### ISSUE TITLE
Revolver

### ISSUE THREAD

**Issue by inot** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#12]
Hello, add please Revolver (weapon_revolver) 850$ price, no armor, no granate, no kit.

**Comment by RavageCS** [comment]
I have added it to my fork. It's not possible to have revolver on pistol rounds so it's only enabled on gun rounds. My fork is customized for my needs, but at the very least you could use it as an example.

**Comment by BatMen** [comment]
I'm going to release a big new update soon this evening. Just edit readme.md file.
