### ISSUE TITLE
Molotov can't be used randomly

### ISSUE THREAD

**Issue by emko** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#16]
Randomly molotov is unable to be used you press the left click nothing happens and then randomly it lets you use it.

**Comment by emko** [comment]
also i didn't configure anything its using all the defaults

**Comment by BatMen** [comment]
Weird stuff. I don't think this can be due to retakes plugin. Mine is only giving you weapons on start of the side. Maybe when the menu to choose weapon appears.
