### ISSUE TITLE
No grenades

### ISSUE THREAD

**Issue by Marounda** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#17]
Hello,

I can't understand why, but when i'm trying to use your plugin, i don't have any grenades...

I tried to create an autoexec with : 
sm_retakes_weapon_nades_enabled 1
sm_retakes_weapon_allow_nades_on_pistol_rounds 1

I tried to add this on the server.cfg, but it's the same...
I don't have any grenades, it's ok for another guy i know.

I only use metamod/sourcemod plugins and retake...

If you can help me, i'll thank you !

**Comment by BatMen** [comment]
Hello,

Check those cvars, which are the max nade per type and per side.
```
sm_retakes_weapon_nades_hegrenade_ct_max 1
sm_retakes_weapon_nades_hegrenade_t_max 1
sm_retakes_weapon_nades_flashbang_ct_max 1
sm_retakes_weapon_nades_flashbang_t_max 1
sm_retakes_weapon_nades_smokegrenade_ct_max 1
sm_retakes_weapon_nades_smokegrenade_t_max 1
sm_retakes_weapon_nades_molotov_ct_max 1
sm_retakes_weapon_nades_molotov_t_max 1
```

If you try to have only pistol mode, maybe you've got this cvar wich does not allow you to buy more than 800$ on pistol round. For example, if you choose to have deagle, you won't have any nade. If you chose to gave fiveseven, you can only have 1 HE, 1 flash or 1 smoke, etc...
```
sm_retakes_weapon_mimic_competitive_pistol_rounds 1
```

With this cvar and mayber the other max nades per side, this can be a problem to have some nades.

**Comment by Marounda** [comment]
Hello, in fact, if I restrict in the gameserver.cfg the nades, it won't function... u_u" I'm sorry for the useless disturbing ! Thanks for your fast answer :)

**Comment by BatMen** [comment]
No problem. I can handle some issues ;)

**Comment by AndreAntG** [comment]
Hello, I know this issue is closed, but can you explain to me where can I add does commands?
