### ISSUE TITLE
[Suggestion] Pistol rounds

### ISSUE THREAD

**Issue by L33TGaming** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#2]
Helmet in pistol rounds should be disabled to mimic a competitive environment.

Also if a player chooses a non-default pistol (any pistol other than P2000 / Glock / USP), the player should not have armour.

This goes the same for kits, which should be given to those who do not have a non-default pistol. 

The above is for pistols rounds only.

**Comment by BatMen** [comment]
This Is a good idea. I think I should add just one convar like retakes_weapon_mimic_competitive_pistol_rounds or something like that. 

I don't think we should add multiple convars for this feature.

What do you think?

**Comment by billgates8889** [comment]
I think that's great, nice and simple.

Not sure how complex you are willing to take the plugin but here's an extension from above.

If player chooses
USP / P200 / Glock - Armour
P250 - Random nade or Kit (Random)
Dual Berrettas / Tec - 9 / Five - Seven / CZ75 -Auto - Random nade
Deagle - Nothing

Or the simple version would be:
Only USP / Glock / P200 - Armour

**Comment by BatMen** [comment]
Yes i was thinking of the 800$ and that you can't buy armor and nade. I'm going to try this feature tonight. I think your suggestions are good.

 - defuse kit should have higher odds than nade like 66% (less nades for CT but this is ok)
 - buy should not be higher than 800$ (i don't remember the price of molotov, i'm at work)

I give you feedback but i have to let the code readable for next updates.

**Comment by L33TGaming** [comment]
That's alright, take your time. No need to rush it out. I'll add in more suggestions when they pop up.

**Comment by BatMen** [comment]
The last commit should do the job but this is not tested at all and i'm not sure about multiple nades. Release is still ok (no update)

**Comment by L33TGaming** [comment]
Nice job on the pistols, however now on gun rounds, armor and helmet are not given.

**Comment by BatMen** [comment]
So your suggestion is : 
 - first test armor chance and give armor if enough money
 - then test kit chance (ct only) and give kit if enough money
 - finally nades ?

Is this case, sm_retakes_weapon_nade_chance_ct is never tested. 
Don't you buy everything you can on pistol round?

For now, you have 66% chance to get armor only when default weapon. 
Then 66% to have a kit and so have less money to buy nades.
Nades are at the ending, always.

**Comment by BatMen** [comment]
Problem for armor/kit/helmet has been solved but not compiled yet. (smx is the old one)

**Comment by BatMen** [comment]
I prefer to have a simpler approch : 
 - armor_only_priority 0 to 10 value (0, never, 10, always)
 - kit_priority 0 to 10 value (0, never, 10, always)

Then you buy random nades if you have enough money. What do you think ?

**Comment by BatMen** [comment]
The release candidate is here. BUT i don't add other convar for now. I think i'm going to add only 2 vars
 - armor_priority_to_kit_then_nades (0 to 10)
 - kit_priority_to_nades (0 to 10)

The release candidate has been tested on an empty server. So i could not test kit stuff because i was terrorist only.

**Comment by BatMen** [comment]
If you have better names for those convars... (i'm french and my english is very...i'm french)

**Comment by L33TGaming** [comment]
Your doing a great job already, those convars should do the job. If there's any money left over either from having armor or kit or nothing then it would be spent to buy nades.

**Comment by BatMen** [comment]
I'm going to make more tests this afternoon/evening. Thank you for your feedback. Then it should be easy to had those 2 convars for pistol rounds after everything is fine (this should be an easy update)

**Comment by Dartdiddl** [comment]
On full gun rounds:
Just a slight problem, I'm fairly sure the kits are handed out to CT's are being affected by the player's pistol choice.

Seems to be so also on my Server

**Comment by BatMen** [comment]
This is it ! I hope. 

Kit problem is solved.

I added some verifications about max grenades for the server config on which the plugin is executed (max flashbang and max nades). Without it, you've got nades on the floor :dancer:

**Comment by L33TGaming** [comment]
Fantastic job, really loving the plugin at the moment. Plugin's working fine with no problems yet. Will post back if any does arise.
