### ISSUE TITLE
[Bug] sm_retakes_weapon_gunrounds n plays n+1 rounds

### ISSUE THREAD

**Issue by L33TGaming** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#4]
The value of sm_retakes_weapon_gunrounds will cause the server to play n+1 rounds.

E.g.

sm_retakes_weapon_gunrounds 5

Server will play 6 pistol rounds before having a full gun round.

**Comment by BatMen** [comment]
this will be fixed in the next release.
