### ISSUE TITLE
Always get kits

### ISSUE THREAD

**Issue by zoidbergwill** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#8]
Is it currently possible to set it to always get kits in competitive pistol rounds? I know it's not really realistic, so it wouldn't be an accurate mimic, but people always dawdle with getting to the bomb and don't communicate properly about dropped kits.

Or would I need to edit the source and compile it myself?

Thanks in advance.

**Comment by BatMen** [comment]
You can simply deactivate sm_retakes_weapon_mimic_competitive_pistol_rounds. This does not remove pistol round, just remove the limitation of 800$ for each pistol round. Always kevlar/helmet (if you set the options to 1), and defusal kti.

A new update will add 2 convars with "probability" to have kevlar and defusal kit on competitive pistol round, from 0 to 10. If you set 10, it means 100%, so everbody will have defusal kit. Can't give a release date, it needs tests.

**Comment by zoidbergwill** [comment]
Awesome, thanks. 

I enjoy the non-guaranteed kevlar, so I'll wait for the update. Thanks.

**Comment by BatMen** [comment]
Please give a try with v0.2.0. Some cvars have been added. I did some of them weeks ago. So I'm not sure this can do what you wanted.

**Comment by zoidbergwill** [comment]
This is awesome, really like the improvements. It does sort of achieve it now. My modifications give kits without checking if they could've afforded it, but yours is a better general solution. Awesome work. Gonna consider this a `wontfix`.
