### ISSUE TITLE
Plugin causes crashes with new CSGO update

### ISSUE THREAD

**Issue by L33TGaming** [BatMen/csgo-retakes-splewis-convar-weapon-allocator#9]
The latest update v1.35.0.2 is causing sporadic crashes with this plugin loaded. 

Crash ID's to help you with the investigation:
IZMF-JLSP-U6EE
3OOE-GQ2U-N3D2
4VHC-UJ5A-B2XQ
NDXH-HUFL-7XDA
S6QM-AOPF-UJT7

**Comment by BatMen** [comment]
I don't have any clue of what to do with this
